#-- Programming language
language: python
python:
  - "3.8"
#-- Command to install dependencies
install:
  - pip install -r requirements.txt

#-- Travis ci testing
services:
  - docker
before_install:
  - docker pull tiangolo/meinheld-gunicorn-flask:python3.7
script:
  - docker build -t travis-ci-build .
